name: 24/7 YouTube Live Loop

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Start Continuous Streaming
      run: |
        ffmpeg -loop 1 -f image2 -i lv.png -stream_loop -1 -i audio.mp3 -c:v libx264 -preset ultrafast -tune stillimage -b:v 1000k -maxrate 1000k -bufsize 2000k -pix_fmt yuv420p -g 30 -c:a aac -b:a 96k -ar 44100 -async 1 -f flv "rtmp://://youtube.com{{ secrets.YOUTUBE_STREAM_KEY }}"
